name: Test build Actions

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    name: Build dic
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@feature/edit_new_github_actions_20200701
      - uses: actions/checkout@v2
        with:
          repository: y-fujii77/sandbox
      - run: ls -l
#       - run: chmod +x hello.sh
      - run: ./hello.sh
#       - run: echo "hello, actions"
